### ISSUE TITLE
H2L transform not used

### ISSUE THREAD

**Issue by andravin** [gan3sh500/octaveconv-pytorch#2]
https://github.com/gan3sh500/octaveconv-pytorch/blob/c23335270c366469f2c419b3b668e864a7f9e425/octconv.py#L26

self.H2L is defined in the initializer but not never used in the forward method.

**Comment by gan3sh500** [comment]
@andravin just saw and fixed it. it was supposed to be done before pooling.

**Comment by andravin** [comment]
Actually the paper pools (ie downsamples) before the H->L projection, which reduces the number of operations, because the projection happens at low resolution instead of high resolution.

**Comment by gan3sh500** [comment]
@andravin I'll fix this and the other issue and push together.
